# Generated by Django 5.2 on 2025-04-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandsensor', '0002_socialpost_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='approved_brands',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='family_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='interest_filter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
