# Generated by Django 5.1.7 on 2025-04-04 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandsensor', '0003_userpreference_approved_brands_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('sentiment', 'Sentiment Analysis'), ('topic', 'Topic Classification'), ('toxicity', 'Toxicity Detection'), ('engagement', 'Engagement Prediction'), ('relevance', 'Relevance Scoring')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.FileField(upload_to='ml_models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='MLPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(max_length=20)),
                ('prediction_value', models.FloatField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter')], max_length=20)),
                ('platform_username', models.CharField(max_length=100)),
                ('connection_type', models.CharField(choices=[('friend', 'Friend'), ('family', 'Family'), ('acquaintance', 'Acquaintance'), ('colleague', 'Colleague'), ('followed', 'Followed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('trust_level', models.IntegerField(default=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name='socialpost',
            options={'ordering': ['-collected_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='socialpost',
            name='automated_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='bizfluencer_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='connection_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='content_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='engagement_prediction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='external_links',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='hashtags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='image_urls',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='is_job_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='mentions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='negative_indicators',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='original_user',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='positive_indicators',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='relevance_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='topic_vector',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='toxicity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='bizfluencer_filter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='bizfluencer_threshold',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='excluded_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='favorite_hashtags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='hide_job_posts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='hide_sponsored',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='high_sentiment_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='max_content_length',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='sentiment_threshold',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='show_verified_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['platform'], name='brandsensor_platfor_7ec9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['is_friend'], name='brandsensor_is_frie_5f264d_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['is_family'], name='brandsensor_is_fami_bfc554_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['verified'], name='brandsensor_verifie_458223_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['category'], name='brandsensor_categor_f79804_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['sentiment_score'], name='brandsensor_sentime_081e74_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['bizfluencer_score'], name='brandsensor_bizflue_a7d936_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['is_sponsored'], name='brandsensor_is_spon_2c66cd_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['is_job_post'], name='brandsensor_is_job__ec8187_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mlmodel',
            unique_together={('model_type', 'version')},
        ),
        migrations.AddField(
            model_name='mlpredictionlog',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brandsensor.mlmodel'),
        ),
        migrations.AddField(
            model_name='mlpredictionlog',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_logs', to='brandsensor.socialpost'),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='socialconnection',
            unique_together={('user', 'platform', 'platform_username')},
        ),
    ]
