# Generated by Django 5.1.7 on 2025-04-04 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandsensor', '0005_apikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('friends_only', models.BooleanField(default=False)),
                ('family_only', models.BooleanField(default=False)),
                ('interest_filter', models.CharField(blank=True, max_length=100)),
                ('approved_brands', models.TextField(blank=True)),
                ('hide_sponsored', models.BooleanField(default=True)),
                ('show_verified_only', models.BooleanField(default=False)),
                ('excluded_keywords', models.TextField(blank=True)),
                ('favorite_hashtags', models.TextField(blank=True)),
                ('bizfluencer_filter', models.BooleanField(default=False)),
                ('bizfluencer_threshold', models.IntegerField(default=3)),
                ('high_sentiment_only', models.BooleanField(default=False)),
                ('sentiment_threshold', models.FloatField(default=0.2)),
                ('hide_job_posts', models.BooleanField(default=False)),
                ('max_content_length', models.IntegerField(blank=True, default=2000, null=True)),
                ('icon', models.CharField(default='filter', max_length=50)),
                ('color', models.CharField(default='primary', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
