# Generated by Django 5.1.7 on 2025-04-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandsensor', '0006_filterpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='browser_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='filter_manipulative',
            field=models.BooleanField(default=True, help_text='Filter out manipulative content'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='sentiment_preference',
            field=models.FloatField(default=0, help_text='User preference for content sentiment (-1 to 1)'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='approved_brands',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='excluded_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='favorite_hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='interest_filter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='max_content_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='sentiment_threshold',
            field=models.FloatField(default=0.3),
        ),
    ]
