# Generated by Django 5.2 on 2025-04-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandsensor', '0007_userpreference_browser_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='original_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
