# Generated by Django 5.1.7 on 2025-04-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brandsensor', '0008_socialpost_original_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='original_url',
        ),
    ]
