# Generated by Django 5.1.7 on 2025-04-08 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brandsensor", "0010_socialpost_manipulative_patterns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialpost",
            name="manipulative_patterns",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="browser_notifications",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="dark_mode",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="email_notifications",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="filter_manipulative",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="sentiment_preference",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="socialpost",
            name="engagement_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="platform_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="user_category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="user_sentiment",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="filter_sexual_content",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="approved_brands",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="excluded_keywords",
            field=models.TextField(blank=True, default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="favorite_hashtags",
            field=models.TextField(blank=True, default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="interest_filter",
            field=models.CharField(blank=True, default=[], max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="max_content_length",
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="sentiment_threshold",
            field=models.FloatField(default=0.2),
        ),
        migrations.AddIndex(
            model_name="socialpost",
            index=models.Index(
                fields=["platform_id"], name="brandsensor_platfor_214751_idx"
            ),
        ),
    ]
