# Generated by Django 5.1.7 on 2025-04-08 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brandsensor", "0013_add_filter_sexual_content_to_filterpreset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="socialpost",
            name="brandsensor_platfor_214751_idx",
        ),
        migrations.RemoveIndex(
            model_name="socialpost",
            name="bs_platfor_id_idx",
        ),
        migrations.RemoveField(
            model_name="filterpreset",
            name="filter_sexual_content",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="filter_sexual_content",
        ),
        migrations.AddField(
            model_name="socialpost",
            name="content_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="socialpost",
            index=models.Index(
                fields=["content_hash"], name="brandsensor_content_2abd9c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="socialpost",
            constraint=models.UniqueConstraint(
                fields=("user", "content_hash"), name="unique_content_per_user"
            ),
        ),
    ]
