# Generated by Django 5.1.7 on 2025-04-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brandsensor", "0015_restore_filter_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="behaviorlog",
            name="action",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="behaviorlog",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="behaviorlog",
            name="platform",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="behaviorlog",
            name="behavior_type",
            field=models.CharField(
                choices=[
                    ("popup", "Popup"),
                    ("tracker", "Tracker"),
                    ("urgency", "Urgency Message"),
                    ("buzzwords", "Buzzwords"),
                    ("collect_posts", "Collect Posts"),
                    ("update_preferences", "Update Preferences"),
                    ("feedback_category", "Feedback Category"),
                    ("feedback_sentiment", "Feedback Sentiment"),
                    ("feedback_relevance", "Feedback Relevance"),
                    ("feedback_hide", "Feedback Hide"),
                    ("feedback_star", "Feedback Star"),
                    ("delete_api_key", "Delete API Key"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="behaviorlog",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="brandsensor.brand",
            ),
        ),
        migrations.AlterField(
            model_name="behaviorlog",
            name="count",
            field=models.IntegerField(default=1),
        ),
    ]
