# Generated by Django 5.1.7 on 2025-04-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brandsensor", "0016_enhance_behaviorlog_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="browser_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
