# Generated by Django 5.1.7 on 2025-04-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brandsensor', '0019_add_socialpost_image_analysis'),
    ]

    operations = [
    ]
