# Generated by Django 4.2.7

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('api', 'API Error'), ('messaging', 'Messaging Error'), ('dom', 'DOM Error'), ('permissions', 'Permissions Error'), ('authentication', 'Authentication Error'), ('extension', 'Extension Error'), ('general', 'General Error')], max_length=20)),
                ('error_message', models.TextField()),
                ('error_metadata', models.JSONField(default=dict)),
                ('browser', models.CharField(max_length=255)),
                ('extension_version', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['error_type'], name='dashboard_er_error_t_323a26_idx'),
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['timestamp'], name='dashboard_er_timesta_f46510_idx'),
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['resolved'], name='dashboard_er_resolve_d81c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['extension_version'], name='dashboard_er_extensi_f7780a_idx'),
        ),
    ] 