# Generated by Django 3.2.25 on 2025-04-28 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('keyword', 'Keyword'), ('hashtag', 'Hashtag'), ('account', 'Account'), ('content_type', 'Content Type')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('is_include', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilteredContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('photo', 'Photo'), ('video', 'Video'), ('link', 'Link')], max_length=20)),
                ('content_id', models.CharField(max_length=255)),
                ('content_data', models.JSONField()),
                ('engagement_data', models.JSONField(default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('threads', 'Threads')], max_length=20)),
                ('account_id', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=512)),
                ('refresh_token', models.CharField(blank=True, max_length=512, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('preferences', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='errorreport',
            name='dashboard_er_error_t_323a26_idx',
        ),
        migrations.RemoveIndex(
            model_name='errorreport',
            name='dashboard_er_timesta_f46510_idx',
        ),
        migrations.RemoveIndex(
            model_name='errorreport',
            name='dashboard_er_resolve_d81c0b_idx',
        ),
        migrations.RemoveIndex(
            model_name='errorreport',
            name='dashboard_er_extensi_f7780a_idx',
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['error_type'], name='dashboard_e_error_t_bcf529_idx'),
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['timestamp'], name='dashboard_e_timesta_8f61f0_idx'),
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['resolved'], name='dashboard_e_resolve_e0687f_idx'),
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['extension_version'], name='dashboard_e_extensi_60e574_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filteredcontent',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.socialmediaaccount'),
        ),
        migrations.AddField(
            model_name='filteredcontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentfilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediaaccount',
            unique_together={('user', 'platform', 'account_id')},
        ),
        migrations.AlterUniqueTogether(
            name='filteredcontent',
            unique_together={('social_account', 'content_id')},
        ),
        migrations.AlterUniqueTogether(
            name='contentfilter',
            unique_together={('user', 'filter_type', 'value')},
        ),
    ]
