# Generated by Django 3.2.25 on 2025-04-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20250428_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
